name: sequence_flow
description: "HTN Planning System for visualizing and managing hierarchical task networks."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.1
  
  # Graph visualization
  graphview: ^1.2.0
  
  # Utilities
  uuid: ^4.3.3
  equatable: ^2.0.5
  
  # Data handling
  json_annotation: ^4.8.1
  http: ^1.2.1
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
